CREATE TABLE [dbo].[BookOnlineStore]
(	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
[CreatedOn] DATETIME NULL, 
    [ISBN] NVARCHAR(50) NULL, 
    [OnlineLink] NVARCHAR(1000) NULL,    PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

