USE [master]
GO

/****** Object:  Database [bookreview-book-db]    Script Date: 2/9/2019 4:22:50 PM ******/
CREATE DATABASE [bookreview-book-db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bookreview-book-db', FILENAME = N'/var/opt/mssql/data/bookreview-book-db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bookreview-book-db_log', FILENAME = N'/var/opt/mssql/data/bookreview-book-db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [bookreview-book-db] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bookreview-book-db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bookreview-book-db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bookreview-book-db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bookreview-book-db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bookreview-book-db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bookreview-book-db] SET ARITHABORT OFF 
GO

ALTER DATABASE [bookreview-book-db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bookreview-book-db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bookreview-book-db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bookreview-book-db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bookreview-book-db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bookreview-book-db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bookreview-book-db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bookreview-book-db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bookreview-book-db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bookreview-book-db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bookreview-book-db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bookreview-book-db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bookreview-book-db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bookreview-book-db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bookreview-book-db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bookreview-book-db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bookreview-book-db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bookreview-book-db] SET RECOVERY FULL 
GO

ALTER DATABASE [bookreview-book-db] SET  MULTI_USER 
GO

ALTER DATABASE [bookreview-book-db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bookreview-book-db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bookreview-book-db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bookreview-book-db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bookreview-book-db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bookreview-book-db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [bookreview-book-db] SET  READ_WRITE 
GO

USE [bookreview-book-db]

GO

CREATE TABLE [dbo].[Book]
(	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[AuthorName] [nvarchar](50) NOT NULL,
	[PublisherName] [nvarchar](50) NULL,
	[Price] [int] NOT NULL,
	[Discount] DECIMAL(5, 2) NOT NULL,
	[Language] [nvarchar](50) NOT NULL,
	[PublicationYear] [int] NULL,
	[Image] [nvarchar](200) NOT NULL,
	[Details] [nvarchar](max) NULL,
[CreatedOn] DATETIME NULL, 
    [ISBN] NVARCHAR(50) NULL, 
    PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

BEGIN TRY
    BEGIN TRAN
		BEGIN
			DECLARE @CurrentDateTime DateTime
			SET @CurrentDateTime = (SELECT GetDate())

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Someone Like You', N'Durjoy Datta', N'Penguin', 140, CAST(0.42 AS Decimal(5, 2)), N'English', 2013, N'someone-like-you-400x400-imadht2fay9nmfuf.jpeg', N'Someone Like You is a story about friendship, love, and betrayal, featuring the lives of five individuals as they face the trials and tribulations of growing up and heading off to college. Niharika Singh is the protanist of Someone Like You. She is a normal girl with whom many young women can identify with. Shy, having low self esteem, and lacking confidence, Niharika feels nonexistent and ugly, until the day her sister Simran gives her a makeover. This transforms Niharika, and helps her realize that she is a beautiful, young woman after all. She soon decides to attend college in a new city. Niharika’s adventure truly begins when she befriends three boys, Karthik, Akshat, and Tanmay. Of the three, Tanmay becomes her best friend, Akshat remains out of bounds, because he is her sister’s ex-boyfriend, and Karthik remains a mystery, for whom Niharika has conflicted feelings. But later, Niharika discovers that his aggressiveness is simply a blanket to hide his past. She also es on to make friends with Pia, who is also her roommate. Things start to spice up when Tanmay develops an interest for Pia. Pia begins reciprocating the same, but she is also involved in a long distance relationship with another boy named Vishal. Niharika and Akshat also begin to question their feelings for each other, adding more spice to the saga.', @CurrentDateTime, N'9780143417699')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Secret Wish List', N'Preeti Shenoy', N'Westland', 175, CAST(0.42 AS Decimal(5, 2)), N'English', 2012, N'the-secret-wish-list-400x400-imadkuygztrkfhpz.jpeg', N'Published in 2012, The Secret Wishlist is a poignant novel about friendship, relationships and following one’s heart in order to find inner happiness. The Secret Wish List is a riveting story about the protanist Diksha, who at the tender age of 16 lives the life of a typical carefree teenager. She juggles school work and fun, amidst schoolgirl crushes on boys including Ankit, and ssip and girl talk with her best friend. However, one day, an innocent crush explodes into a chain of irreversible events that result in changing her life forever. 18 years later, Diksha, the feisty, fun loving teenager, has been replaced by a very different version of her younger self. Now, at the age of 35, she is a jaded and bored housewife beneath the facade of a happily married woman. Married at 19 to Sandeep, a successful professional, and mother to a bright young boy, she is an unhappy woman who is dissatisfied in her loveless marriage and trapped in a domestic setting she no longer feels connected to. When an unfortunate incident involving her cousin’s husband takes place, it brings all her unmet hopes and desires to the fore, opening up possibilities Diksha never felt she would find again. Stemming from a desire to fulfill her hopes and dreams, a secret wish list is born. It urges Diksha to following her heart and explore the possibilities of unrequited love that she denied herself for so many years. The Secret Wish List is a sensitive account of a woman’s soul searching and attempts at self discovery in order to find true happiness. Its intriguing storyline tackles the moral dilemma and temptations of an extramarital affair, the elusive nature of true love and whether it really does exist, the fragility of friendship and relationships, and the significance of one’s dreams.', @CurrentDateTime, N'9789382618188')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Love Stories That Touched My Heart', N'Ravinder Singh', N'Metro Reads', 140, CAST(0.42 AS Decimal(5, 2)), N'English', 2012, N'love-stories-that-touched-my-heart-400x400-imadjvruag5rzgxn.jpeg', N'Weve all experienced the first flush of love and remember the lingering fragrance of it. For ages Love has remained one of the most cherished experiences that everyone wishes to live through at least once. Humanity, time and again, has coined many definitions to describe this beautiful emotion, but this small word is a feeling that cant simply be defined. It has to be narrated . . . in the form of stories love stories. Love Stories That Touched My Heart is a collection of such stories from readers who have a tale to tell, shortlisted from over 2000 entries that were submitted in a competition conducted by Penguin India.', @CurrentDateTime, N'9780143419648')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Can Love Happen Twice?', N'Ravinder Singh', N'Penguin', 140, CAST(0.42 AS Decimal(5, 2)), N'English', 2012, N'can-love-happen-twice-400x400-imadarucay5gxr5g.jpeg', N'Can Love Happen Twice? is the sequel to I Too Had a Love story by Ravinder Singh. On Valentine''s day, Ravin, Amardeep, Happy, and Manpreet are to attend ''Raat gayi, baat baki'', a radio talk show in Chandigarh. But Ravin fails to show up. Where is Ravin and what has happened to him? As the evening progresses, Ravin''s story is unravelled. Devastated by the death of his girlfriend Khushi in a road accident, Ravin is trying his best to cope with this loss. He immerses himself in work which takes him to Belgium. A coincidental meeting with Simar, an MBA student from India, captures his attention and threatens to change his life yet again. The novel effectively captures the life and moments of Ravin''s life after Khushi''s death. Does Ravin really love Simar? Can love really happen twice? Will Ravin be able to accept Simar and move on with his life? What are the untold secrets of Ravin''s life? The book offers a fresh perspective on the complex matters of love, loss, and infatuation. Can Love Happen Twice? is loosely based on the author’s life, and it takes the reader on an emotional journey as Ravin tries hard to make sense of the world around him. Employing simple dialogues, the book brings to light the new age dilemmas such as misunderstandings in relationships, parental concerns, and moving on in life.', @CurrentDateTime, N'9780143417231')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Uff Ye Emotions: A Collection of Award Winning Love Stories', N'Vinit K. Bansal', N'Mahaveer Publishers', 140, CAST(0.42 AS Decimal(5, 2)), N'English', 2013, N'uff-ye-emotions-a-collection-of-award-winning-love-stories-400x400-imadhesu5scdsekz.jpeg', N'Perhaps, emotions are the most beautiful things in the world which cannot be seen or even touched. Interestingly, they can only be felt with the heart. Love is the purest and primary among them with its various shades. We all have our own definitions of this magical word, but, its beyond explanation. It is always around us. The very existence of this beautiful universe is founded on love only. Love has been the most talked about subject since ages and has always come to us through stories and became a part of us. Almost each of us has experienced the magic of this emotion in one form or other in our lives. Uff Ye Emotions is trying to recapture the magic of love through 12 beautiful award winning stories which were selected after a nation-wide contest. Stories in this anthology are soaked with intense emotions: Adoration, affection, love, friendship, fondness, attraction, caring, compassion, sentimentality, desire, lust, passion, longing, infatuation, envy, jealousy etc. which truly complete our lives. Love stories from diverse age groups, from different corners of the country and containing different shades of love.', @CurrentDateTime, N'9789350880388')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Oliver''s Story', N'Erich Segal', N'Hodder & Stoughton', 299, CAST(0.30 AS Decimal(5, 2)), N'English', 2013, N'oliver-s-story-it-takes-someone-very-special-to-forget-the-love-of-your-life-400x400-imadh6vgwb2z45ht.jpeg', N'Oliver Barrett IV found his true soulmate when he met and fell in love with Jenny Cavilleri. Their love was magical, exhilarating... though heartbreakingly brief, it was enough to last a lifetime. Or so Oliver told himself. Two years have passed since Jenny was taken from him, and Oliver truly believes he will never love again. Then one day Marcie - beautiful and mysterious - enters his world and suddenly the future holds a lden new promise. With all the excitement and emotion that made LOVE STORY a worldwide bestseller, here is a stirring romantic novel that sweeps from New York''s fashionable East Side to a snowy Christmas in Massachusetts to a shattering moment of truth in exotic Hong Kong - the story of one young man''s journey out of sadness and into love.', @CurrentDateTime, N'9781444768404')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Love Endeavors', N'Vikram Sethi', N'Notion Press', 255, CAST(0.05 AS Decimal(5, 2)), N'English', 2013, N'love-endeavors-400x400-imadhepbzwdzvsch.jpeg', N'Kavi and Sara are madly in love with each other, getting delighted to a ravishing degree! But something es terribly wrong, splitting them up as hell with a no hope of rescue! Then, suddenly after 2 years of killing separation. Once again, Destiny makes them face each other circumstantially, giving away a lden chance to revive their relationship! What''s nna happen? Would love endeavor to spill its spunk over them? Would love endeavor to cast its magical spell over them, to revive their relationship, to unite them once again? Love is regarded as the d and vice-versa. But always the barrier of Astrology, Religion, Society claimed themselves bigger than the elysian ''love'' and always caused impediments, putting the shackles of ''Terms & Condition'' in the path of Lovers for prolonged centuries!!! But Out of eism, they always forget, love knows no conditions! Its the unconditional and unbounded ocean of perpetual bliss! Unwrap the ''Torrid Love Affair'' of ''Astrologically Incompatible Couple, struggling against the destiny! An eternal love story, trapped in the clutches of astrology and religion, uncovering how their ghastly destiny enforce them to split up pathetically, landing them into heartrending ''state of affairs'' besides phenomenal love amid them. One after another obstruction mops up their life cataclysmically, eventually dragging them into a woeful plight!!!But every dark night comes with a resplendent dawn! For every dark night, there''s a brighter day! While facing the glooming challenges, we often do forget that Sun is always shining above the clouds... And as it appears, our life becomes shining like the ld! Similarly, The sun of ''Cosmic Grace'' manifests enigmatically,transforming their lives miraculously just in a jiffy and give them the quickest redemption from their sinister, cursed and wretched life like never heard, like never seen before!!! An erotically romantic, spine-tingling, bewitchingly captivating, most redolent and perhaps the most randiest ''Love Story'' of an everlasting season called ''Love! The real life love story with a perfect blend of spiritualism, visualizing the love, love & love as the one and only eternal religion!!! Which actually endeavors to bloom our lives like the paradise... And capable to erase the deep-rooted, set of past bad karmas, which are indeed the major cause of our present sufferings!', @CurrentDateTime, N'9789382447276')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Third Bullet', N'Stephen Hunter', N'Simon & Schuster', 699, CAST(0.40 AS Decimal(5, 2)), N'English', 2013, N'the-third-bullet-400x400-imadzrf6vedwtpj9.jpeg', N'In The Third Bullet, the protanist, Bob Lee Swagger, tries to find out why the third bullet, which was instrumental in the assassination of the former American President, John F. Kennedy, exploded. Many investigators and authors who followed the case remain clueless about the third bullet. The book has its roots in the first novel that the author wrote, Point Of Impact. Through the book, the author aims to expose the mastermind behind the explosion of the third bullet that killed the President. In the beginning of the book, an author, who is investigating the assassination is run down by a car. His wife, convinced that it was not an accident but a murder, approaches Bob Lee Swagger for help in the investigation. He sets out to explore several unanswered questions relating to the assassination. The points that puzzle him are the explosion of the third bullet and why Lee Oswald headed back to his place to retrieve the pistol instead of carrying it with him. Swagger also tries to understand how the assassination was planned before the route that the ex-President was ing to take was announced. The Third Bullet takes an interesting turn when CIA operative, Hugh Meachum, comes into the scene with secrets that nobody knows of. But, he is unwilling to reveal them for various reasons. As they travel across the world in search of the answers, the actual story behind the mystery slowly unravels.', @CurrentDateTime, N'9781451640205')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Hit', N'David Baldacci', N'Pan Macmillan', 550, CAST(0.50 AS Decimal(5, 2)), N'English', 2013, N'the-hit-400x400-imadku9feqx8zkjz.jpeg', N'The Hit, published in 2013, has a thrilling plot. The protanist, Will Robie, is an American vernment employed assassin. His job is to kill the worst possible enemies of the nation, thereby saving thousands of lives. This hitman has now been given a new assignment, where he has to kill Jessica Reel, his former colleague. She too is as od a killer as Robie, but she suddenly seems to have turned rogue. Her targets are members of the intelligence agency that she was once a part off. Reel leaves behind a trail of death wherever she es. The Hit focuses on how Robie is sent on this mission to eliminate Reel, as only a killer can catch another killer. This master assassin is told to set a trap, but the rogue agent is tough and highly skilled. Robie pursues his former colleague, and as the plot unveils itself, readers learn that maybe Reels betrayal holds the key to some dark secrets that would shock the globe. The author has beautifully captured the paranoia and loneliness that agents in this line of work  through. The Hit is a fast paced and pulse pounding novel. It weaves into its storyline many factors, such as trust, betrayal, paranoia, and more. The Hit is an exciting, action packed, with surprises. The book was published in 2013 and was Number 1 on the New York Times Best-Sellers list.', @CurrentDateTime, N'9781447229902')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'A Degree in Death', N'Ruby Gupta', N'Alchemy Publishers', 225, CAST(0.29 AS Decimal(5, 2)), N'English', 2012, N'a-degree-in-death-400x400-imadfw74gfzsbbng.jpeg', N'The midnight murder of a student in the sleepy town of Dehradun rouses everyone with suspicion and alarm. Violence is incomprehensible in this institute located at the foothills of the Himalayas. With no clues or suspects, the police are unable to catch the killer. Professor Shantanu Bose, an eminent nano-expert and Dean of Research and Development, is deeply troubled at this havoc caused to his institute. Determined to bring back the peaceful academic environment of the campus, he begins his own investigation. Fear mounts as more bodies are discovered one after the other. Soon the professor finds himself in grave danger. as he realizes he is being stalked and his every move is being observed. Yet. he persists with his enquiry and discovers that the truth is more startling than what anyone could have imagined. ', @CurrentDateTime, N'9788180460845')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Edge of the Machete', N'Abhisar Sharma', N'Westland', 250, CAST(0.32 AS Decimal(5, 2)), N'English', 2012, N'the-edge-of-the-machete-400x400-imadd2ekeqhgatcs.jpeg', N'To eliminate Jasons killer, mez has to infiltrate a conglomeration of the most ferocious terror outfits in The Beast as Sarfaraz Khan. But as the boundaries between mez and Sarfaraz blur, the CIA agent must not only plunge headlong into the battle in the Khyber, but also wage a war within. Simultaneously, Indian journalist Rahul Sharma, kidnapped and held hostage within The Beast, must find a way back to the woman he loves. And British white Muslim, Shaun Marsh aka Shahid Khan, sucked into the gathering at the Khyber, must learn to exorcise the ghosts of the past. Most of all, all three must try to escape the edge of Aamir Sherzais machete. Will they get away unscathed? Or meet a fate similar to Jasons? Find out in this captivating thriller! ', @CurrentDateTime, N'9789381626672')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Krishna Key', N'Ashwin Sanghi', N'Westland', 250, CAST(0.50 AS Decimal(5, 2)), N'English', 2012, N'the-krishna-key-400x400-imadayvmeqfbbwyg.jpeg', N'The Krishna Key revolves around a powerful legacy left behind by Krishna. This legacy is wanted by a large number of people, most of whom are even willing to kill for it. The book focusses on a professor, the main character, who has to beat the cops and others in the quest for this legacy and ensure that it is not misused. Professor Ravi Mohan Saini specializes in mythology and its hidden symbols and secrets. One of his friends, a symbologist named Anil Varshney, tells him of The Krishna Key, a collection of sacred and powerful objects that if put together, could have some astounding results. Anil Varshney is murdered and that starts the professor’s quest in earnest. A series of gruesome murders take place. The character, Taarak Vakil, thinks he is the next avatar of Vishnu, Kalki. Fully convinced that he is Kalki, Vakil is after Krishna''s descendants in order to retrieve The Krishna Key. Krishna’s Yadava clan currently has four branches. These are the Varshney, the Saini, the Chhedi, and the Satvat branches. Taarak is after each branch of the ancient Yadava lineage. He thinks he will find the pieces of the puzzle with each one of them. He decides to locate the persons holding each of the pieces, get it and then kill them. He suffers from no remorse for the murders, for he thinks he is d. Ravi Saini now has to get the powerful legacy of Krishna before Vakil, and stop his murderous plans.', @CurrentDateTime, N'9789381626689')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Taj Conspiracy', N'Manreet Sodhi Someshwar', N'Westland And Tranquebar Press', 250, CAST(0.50 AS Decimal(5, 2)), N'English', 2012, N'the-taj-conspiracy-400x400-imad8makhs7eznhz.jpeg', N'Mughal scholar Mehrunisa Khosa stumbles on a conspiracy to destroy the Taj Mahal when she discovers the murder of the Taj supervisor, and the Quranic calligraph on the tomb of Queen Mumtaz altered to suggest a Hindu origin of the Taj Mahal. That urban legend had always existed. Now, though, someone was conspiring to make it come true. In the case of the famed marble monument, all was not on the surface. A vast labyrinth ran underneath closed to visitors where Mehrunisa was trapped once. In a series of suspenseful twists and turns, the action traverses from the serene splendour of Taj Mahal to the virulent warrens of Taj Ganj, from intrigue laden corridors of Delhi to snowy Himalayan hideouts. As a right wing Hindu party ratchets up its communal agenda and Islamic militants plot a terror attack, in the dark corners of his devious mind a behrupiya, a shape shifter, is conniving to divide the nation in two. To save the Taj Mahal, Mehrunisa must overcome a prejudiced police and battle her inner demons as she sifts the multiple strands that lead to the conspirator.', @CurrentDateTime, N'9789381626139')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Malgudi Days', N'R. K. Narayanan', N'Indian Thought Publications', 125, CAST(0.36 AS Decimal(5, 2)), N'English', 2011, N'malgudi-days-400x400-imadat2auzypym2e.jpeg', N'Malgudi Days is a novel that revolves around the happenings in a small fictional village named Malgudi, which is located on the banks of the river Sarayu in South India. This book is a collection of 32 short stories that are highly amusing. The remarkable feature of the stories present in this book is that they are all centered around the lives of mere commoners as they  about their daily routine. The stories present in this book mostly revolve around the relationships among family members as well as the social taboos in the mid-nineties. Through the course of this book, readers are introduced to a ten-year-old lad named Swaminathan, and his two closest friends, Mani and Rajam, whose fun-filled exploits provide a great deal of entertainment to the readers. In another story in this book, Chandran, whose apprehensions about life and issues related to love provide for an interesting read. One of the stories in this book entitled The English Teacher, revolves around incidents in the life of Jagan, and his son Mali. Along with providing the readers with an interesting story, the author also highlights the problem of the generation gap between parents and children. While some of the stories may keep the readers in splits of laughter, certain stories may actually cause the reader to cry, as they establish a connection between themselves and the reader. The stories present in Malgudi Days are highly thought-provoking, and make for a od read for individuals of all age groups. Malgudi Days was published for the first time in the year 1943 by Indian Thought Publications. Put together with a great deal of humor and grace, this classic piece of literature by R. K. Narayan is widely appreciated by its readers to this day. This novel, Malgudi Days, was also adapted into a television series that was aired in the year 1986, by Shankar Nag.', @CurrentDateTime, N'9788185986173')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'To Kill a Mockingbird', N'Harper Lee', N'Random House', 299, CAST(0.41 AS Decimal(5, 2)), N'English', 2010, N'to-kill-a-mockingbird-400x400-imadat2amn7wzuqv.jpeg', N'Atticus Finch lives in the fictional town of Maycomb in Alabama and as it is with the Deep South, the southern traditions of relations in race and gender are at the center of this masterpiece. His daughter, Scout is the narrator of the story and she lives with her widowed father and brother. To Kill A Mockingbird first explores the customs of the South, laying down all the quirks and foibles of the neighbors and people that Scout interacts with through her childhood days. The story of how her brother Jem injured his arm at the elbow is what starts off Scott’s reminiscing journey. This leads them to point out that it was the Ewells who set off the entire string of events that brought about the unsavory incident. And this is what is at the heart of the novel. The narrative that is so delicately handled by Lee is insightful and intuitive. Atticus is appointed by the court to defend a black man, Tom Robinson who has been accused of raping a white girl, Mayella. However the town doesn’t need a trial since they are steeped in prejudice against the coloured people and to them, Robinson is guilty of the crime. However, Atticus defends Tom to the best of his ability that turns the residents of this otherwise sleepy town against him and his family members. For the most part, the townspeople engage in hurling insults at the middle-aged man, which is unacceptable to the sprightly Scout. She along with her brother and their friend, Dill manage to disperse the mob of people but the situation grows worse.  Will Tom Robinson serve time for a crime he did not commit and will Scout lose her love for the South as she had before? A poignantly simple tale of losing innocence and more to the law of society, To Kill a Mockingbird does more than just enlighten people.', @CurrentDateTime, N'9780099549482')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Midnight''s Children', N'Salman Rushdie', N'Vintage', 499, CAST(0.49 AS Decimal(5, 2)), N'English', 2012, N'midnight-s-children-400x400-imadjsauh2gvkhut.jpeg', N'In Midnight’s Children, Saleem, the protanist, has been endowed with telepathic powers as a result of the unusual time that he was born, and these powers allow him to connect with one thousand other such children who were born at that hour. Besides Saleem, the readers are introduced to other characters as well, two of them being Shiva and Parvati, who are also endowed with mysterious powers as a result of being born at that particular time in India’s history. Saleem assembles all of these characters telepathically, and they attempt to understand the relevance of their gift.  The story is based on actual historical facts as well as fiction, and provides the readers with a great deal of insight into the lives of people who lived during the Partition of India. Midnight’s Children highlights the plight of the people and the problems faced by the leaders as well.', @CurrentDateTime, N'9780099582076')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Fountainhead', N'Ayn Rand', N'Signet', 399, CAST(0.49 AS Decimal(5, 2)), N'English', 1996, N'the-fountainhead-400x400-imad9wngvsevjnfy.jpeg', N'The Fountainhead revolves around the dynamic protanist Howard Roark, who defies collectivism with his own brand of philosophy and architecture. He takes a firm stand against worshipping tradition and embraces his own modern art forms. Roark gets expelled from architecture school owing to his non-adherence to conventional guidelines. Roark starkly defies history in favor of a more utilitarian outlook. He highlights materials, location and purpose as the three pillars of architecture. Roark ultimately works for disgraced architectural legend Henry Cameron in New York. At the same time, The Fountainhead also tells the story of Peter Keating, a perfect foil to Roark. Keating holds a job at the renowned Francon & Heyer firm, where he eventually lands a partnership on account of his flattery. Roark starts his own office, but finally lands up at a granite quarry owned by Guy Francon. The novel is also the story of Dominique Francon with whom Roark has a physical and emotional battle throughout the novel. The Fountainhead is an intriguing look at hypocrisy through Roark’s anonymous designs that spur Keating’s success. Eventually Gail Wynand becomes Roark’s friend and patron. Roark even es to trial for dynamiting a building, the designs of which were changed.', @CurrentDateTime, N'9780451191151')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Train to Pakistan', N'Khushwant Singh', N'Penguin', 250, CAST(0.50 AS Decimal(5, 2)), N'English', 2009, N'train-to-pakistan-400x400-imadas3h89nnmwkh.jpeg', N'The story in Train To Pakistan begins at the time of the Partition. The country is being divided into India and Pakistan, and in many places along the border, bloody riots affect the proceedings. The tiny village of Mano Majra remains isolated from these outside conflicts. The Sikhs and Muslims in this village live in peace, and the relationship between the two communities is od. The Muslims work as labourers in the village, while the Sikhs own the land. The story centers around this little village, and how the peace in the community is shattered due to a series of events. When news of the riots reach the village, the different communities express their solidarity and support for each other. But trouble arrives in the form of a train carrying the slaughtered bodies of Hindus and Sikhs from the region that is to be Pakistan. Refugees also arrive from these places, their hearts filled with hatred due to the violence that they have witnessed. Slowly, the peaceful village becomes divided. Meanwhile, a money lender named Ram Lal is murdered in the village. In the wake of the new tense atmosphere, the inspector who has been sent down to keep peace fears that this might trigger angry reactions against all Muslims. As the Muslims prepare to board a train leaving for Pakistan, the inspector tries to divert the others’ attention by arresting people who are not connected with the murder, like Juggut Singh, the never-do-well of the village, an uneducated and volatile young man who has always been in trouble with the law. He is however extremely loyal towards his own village. He knows the gang that committed the murder, but had refused to take part in killing a person from his own village. The other person arrested is an intellectual political activist, Iqbal Singh. During all this, the tension between the communities heats up due to the influx of refugees. The Sikhs and Hindus of the village, who had once stated their willingness to defend their Muslim neighbors against the anger of the refugees, now turn against the Muslims. A violent mob plans to attack the train carrying Muslim refugees to Pakistan. The inspector releases both Juggut and Iqbal, hoping that they would somehow be able to help him save the train. This book does not focus on the major politics of the partition. Instead, it focuses on a tiny and peaceful community that is torn apart by external influences.', @CurrentDateTime, N'9780143065883')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Malgudi Schooldays', N'R. K. Narayan', N'Penguin Classics', 199, CAST(0.37 AS Decimal(5, 2)), N'English', 2009, N'malgudi-schooldays-400x400-imadjkpq2mtakhcj.jpeg', N'Set in pre-independent India, Malgudi Schooldays revolves around little Swami and his many adventures in the fictional town of Malgudi. Swami, the protanist, is a young boy who does not really enjoy school. Often indulging in pranks, school for Swami is a terrible burden. Gazing at trains, entertaining himself by noting different hairstyles and caps, breaking the principal’s window, and running away from school are just a few of the antics that comprise the schooldays of the protanist. Swami, Somu, Mani, Samuel and Shankar are very od friends who often indulge in adventures together. But the dynamics are all about to change when the intelligent and bold Rajam enters the group. The Malgudi Cricket Club or MCC is started and Swami is elected to be the team’s bowler. A star of the team, Swami soon is faced with a new problem. He has to attend the school drill and the cricket coaching at the same time. How will Swami handle the new boy? Will Swami be able to attend the cricket coaching? Or will his misadventures get him into further trouble? Malgudi Schooldays is a highly invirating account of the nostalgic school days of Swami and his friends. Written from the perspective of the young troublemaker, the book revisits the innocence, imagination, and simpler times of childhood.', @CurrentDateTime, N'9780143330981')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'JONATHAN LIVINGSTON SEAGULL A STORY', N'Richard Bach', N'HarperCollins India', 199, CAST(0.40 AS Decimal(5, 2)), N'English', 2005, N'jonathan-livingston-seagull-a-story-400x400-imadat8fmeyfbumn.jpeg', N'Jonathan Livingston Seagull, first published in 1970, is a short novel about a seagull named Jonathan Livingston. The first part of the book shows that unlike other birds, Jonathan is bored of just fighting for food. He wishes to learn all there is to flying, and manages to dive at a speed of two hundred miles per hour. He becomes excited as he is the fastest seagull ever. However, the other birds say that he is recklessly irresponsible and therefore should be banished from the flock. Jonathan doesn''t lose his passion for flying, and continues to practice his skills. One day, he meets two other seagulls who tell him about a wonderful place where all gulls love to fly. Jonathan becomes friendly with a different group of seagulls and befriends the wisest seagull, who guides him to fly in a way that would instantaneously allow him to reach any part of the universe. In the next part of Jonathan Livingston Seagull, the protanist decides to return to his original flock and teach his skills to other seagulls who have been outlawed by their flocks. He also spreads the message of love. Will his students be able to learn from their master? Will the other seagulls accept what he has become and learn from him? Jonathan Livingston Seagull is filled with illustrations by Russell Munson. After a plane crash in 2012, Bach wrote the fourth and last part of Jonathan Livingston Seagull. Within two years of its publication, more than a million copies had been printed. It also reached the No.1 spot on the New York Times bestseller list, and stayed there for 38 weeks. It is the bestselling novel in America as per the Publishers Weekly list. A movie of the same name was also made. In 1973, actor Richard Harris won a Grammy for the audiobook.', @CurrentDateTime, N'9788172235789')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Artemis Fowl and the Last Guardian', N'Eoin Colfer', N'Penguin', 499, CAST(0.49 AS Decimal(5, 2)), N'English', 2012, N'artemis-fowl-and-the-last-guardian-400x400-imadb8fthzuzh7uv.jpeg', N'Artemis Fowl, the titular character, is an Irish teenage criminal mastermind. Along with his bodyguard, Domovoi Butler, and his friends Holly Short and Foaly, he saves the humans and fairies from danger. In the beginning, Artemis Fowl uses his skills to increase his family’s fortune, but later shares his booty and helps the public. The series traces Artemis’ transformation from a selfish criminal to a selfless hero. In Artemis Fowl And The Last Guardian, we find Artemis and his friends up against their old villain Opal Koboi. Opal is adamant on destroying the human beings and becoming the Fairy Queen. She devises a new plan to completely destroy mankind. She plans her release from prison, and opens the magical Berserker''s Gate. When the Berserkers rise, they inhabit the bodies of Artemis'' four-year-old brothers Beckett and Myles Fowl. Butler''s sister Juliet, is also possessed by these demonic creatures that cause mass destruction. How will Artemis and his friends fight against their own families? Will Artemis and Holly be able to return the Berserkers to the portal? Will Artemis and his friends be able to save the planet in time? Or will he be too late?', @CurrentDateTime, N'9780141344331')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Wake', N'Amanda Hocking', N'Pan', 350, CAST(0.34 AS Decimal(5, 2)), N'English', 2012, N'wake-400x400-imadbhrnrmj3wbrn.jpeg', N'Beautiful. Fearless. Dangerous. They''re the kind of girls you envy; the kind of girls you want to hate. Strangers in town for the summer, Penn, Thea, and Lexi have caught everyone''s attention, including the eye of practical Harper. But it''s her sister, Gemma, they''ve chosen to be part of their group. Sixteen-year-old Gemma seems to have it all - carefree, pretty, and falling in love with the boy next door. But her greatest passion has always been the water. She craves late night swims under the stars, where she can be alone yet belong to the sea. Lately she''s had company. Penn, Thea, and Lexi spend their nights dancing, singing, and partying on the cove - and one night Gemma joins them. When she wakes up groggy on the beach the next morning, she knows something has changed.', @CurrentDateTime, N'9781447205722')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Game of Thrones: A Song of Ice and Fire', N'George R.R. Martin', N'HarperCollins Publisher', 499, CAST(0.49 AS Decimal(5, 2)), N'English', 2011, N'game-of-thrones-a-song-of-ice-and-fire-book-1-400x400-imadhktfugaghygp.jpeg', N'Full of adventure, mystery, intrigue, and romance, Game Of Thrones: A Song Of Ice And Fire (Book- 1) TV Tie-in Edition is a fitting opening to one of the most popular fantasy fiction series. The book contains supernatural elements which revolve around the seasons which last decades. The summer is ending and winter is fast approaching. As the cold is on its way back, it is bringing along with it deadly forces. Beyond the protective walls of the kingdom, in the frozen wastes, supernatural forces are making their way to the world of men. In this battle for the throne, replete with death, plunder, tragedy, betrayal, terror, and treachery, two families take centre stage, the Starks and the Lannisters. Lord Eddard Stark, the newly appointed ‘Hand’ of King Robert, has to defend the Iron throne. What happens to King Robert? What does Ned Stark discover that makes him the enemy of the Queen? Will Sansa Stark marry Joffrey? Who is Daenerys Targaryen and how will her actions affect Westeros? This fantasy adventure tale, which takes place in a land of magic, drans, and supernatural creatures, keeps readers spellbound till the very end.', @CurrentDateTime, N'9780007428540')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'A Clash of Kings: A Song of Ice and Fire ', N'George R. R. Martin', N'Harper Voyager', 499, CAST(0.44 AS Decimal(5, 2)), N'English', 2011, N'a-clash-of-kings-a-song-of-ice-and-fire-book-2-400x400-imadhkz8mymsdv46.jpeg', N'A Clash Of Kings is the second book in the fantasy series, A Song Of Ice And Fire, by George R. R. Martin. It picks up from where the first book, A Game Of Thrones, leaves the story, and this book is narrated from the points of view of the nine primary characters, true to the pattern set by the first book in the series.', @CurrentDateTime, N'9780006479895')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Harry Potter And The Deathly Hallows', N'J. K. Rowling', N'BLOOMSBURY PUBLISHING', 599, CAST(0.40 AS Decimal(5, 2)), N'English', 2010, N'harry-potter-and-the-deathly-hallows-signature-edition-400x400-imadbkz2jhz5f6su.jpeg', N'The book opens with Harry Potter''s decision to finally defeat Voldemort. Harry starts on the difficult mission with his friends, Hermione and Ron. Their first target is to find and destroy Voldemort''s remaining Horcruxes. Only then can Voldemort be destroyed. But the task does not seem to be an easy one. Harry has been hearing disturbing rumours about the past life of his previous headmaster, Dumbledore. Often the three friends have to starve. The winter is making their journey more difficult. In the absence of proper planning the progress is slow. Their spirits are low too. They decide to visit dric''s Hollow to look for clues and almost get caught by Voldemort. It appears as though Voldemort knows of their plans in advance. They face many near-death experiences and their morale is very low. The situation worsens when Harry discovers that his magic wand was broken during a battle.  They get excited when they learn about the three mysterious magical objects known as the Deathly Hallows. These three objects give their possessor mastery over death, which just might give Harry a chance to defeat Voldemort.', @CurrentDateTime, N'9781408810606')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Noonshade', N'James Barclay', N'Orion Publishing Group', 450, CAST(0.28 AS Decimal(5, 2)), N'English', 2008, N'noonshade-400x400-imadkv44wkhbn6um.jpeg', N'The enthralling sequel to DAWNTHIEF takes the adventure into a new dimension. The Raven must fight to help the drans of the Brood Kan defend the dimensional rip opened in the skies of Balaia by the casting of Dawnthief. And then they must somehow close the rip. And all the time the Wesmen are rampaging through Balaia, laying waste to its cities and besieging the mages of Julatsa in Dordova.', @CurrentDateTime, N'9780575082793')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Lord of The Rings', N'J. R. R. Tolkien', N'HarperCollins Publisher', 495, CAST(0.40 AS Decimal(5, 2)), N'English', 2005, N'the-lord-of-the-rings-400x400-imadez6ppyjy36mh.jpeg', N'The first part of Tolkien’s epic masterpiece, The Lord of the Rings, now in B format paperback with a black cover based on Tolkien’s own design. Sauron, the Dark Lord, has gathered to him all the Rings of Power – the means by which he intends to rule Middle-earth. All he lacks in his plans for dominion is the One Ring – the ring that rules them all – which has fallen into the hands of the hobbit, Bilbo Baggins. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose. Now published again in B format, J.R.R. Tolkien’s great work of imaginative fiction has been labelled both a heroic romance and a classic fantasy fiction. By turns comic and homely, epic and diabolic, the narrative moves through countless changes of scene and character in an imaginary world which is totally convincing in its detail.', @CurrentDateTime, N'9780007273508')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Throne of Fire', N'Rick Riordan', N'Penguin', 350, CAST(0.46 AS Decimal(5, 2)), N'English', 2012, N'kane-chronicles-the-throne-of-fire-400x400-imadgu4geqbynm4r.jpeg', N'Ever since the ds of Ancient Egypt were unleashed on the modern world, Carter Kane and his sister, Sadie, have been in big trouble. As descendants of the magical House of Life, they command certain powers. But now a terrifying enemy - Apophis, the giant snake of chaos - is rising. If Carter and Sadie don''t destroy him, the world will end in five days'' time. And in order to battle the forces of chaos, they must revive the sun d Ra - a feat no magician has ever achieved. Because first they must search the world for the three sections of the Book of Ra, then they have to learn how to chant its spellsCan the Kanes destroy Apophis before he swallows the sun and plunges the earth into darkness . . . forever?.', @CurrentDateTime, N'9780141335674')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Eragon', N'Christopher Paolini', N'Corgi Childrens', 275, CAST(0.29 AS Decimal(5, 2)), N'English', 2005, N'eragon-400x400-imada5h5ufgtehvr.jpeg', N'When Eran finds a polished stone in the forest, he thinks it is the lucky discovery of a poor farm boy; perhaps it will buy his family meat for the winter. But when the stone brings a dran hatchling, Eran soon realizes he has stumbled upon a legacy nearly as old as the Empire itself. Overnight his simple life is shattered and he is thrust into a perilous new world of destiny, magic and power. With only an ancient sword and the advice of an old storyteller for guidance, Eran and the fledgling dran must navigate the dangerous terrain and dark enemies of an Empire ruled by a king whose evil knows no bounds. Can Eran take up the mantle of the legendary Dran Riders? The fate of the Empire may rest in his hands.', @CurrentDateTime, N'9780552553209')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Lost Symbol', N'Dan Brown', N'Corgi', 299, CAST(0.40 AS Decimal(5, 2)), N'English', 2010, N'the-lost-symbol-400x400-imadaryjh8guqyah.jpeg', N'Robert Langdon, a symbolist from Harvard, is beckoned for a talk at the Capitol Building by his mentor and philanthropist, Peter Solomon. As soon as he arrives, he finds Solomon’s severed hand, left behind by a killer, Mal’akh - a hand that he identifies to be an archaic invitation. Robert understands that the only way to emancipate his friend is to follow the hints and symbols to where they lead him. As soon as he makes his final decision, he is brushed off far behind the frontispiece. He finds himself amidst America’s hidden history - temples, alcoves, and adits. Everything around him seems to lead him to a single, fantastic, and incomprehensible spel. The book, The Lost Symbol, is a heart-pounding thriller that keeps its readers engaged by offering breathtaking surprises on almost every page. It talks about the journey of Robert Langdon, wherein he moves towards ‘The Truth’ - the truth of the symbol that was hidden under a charade of surprises for decades together. A bestseller that was widely pre-ordered before its release, The Lost Symbol sold 1 million copies on the day of its release (September 15, 2009). A film based on The Lost Symbol is being made and produced by Columbia Pictures. The movie is expected to release in 2012.', @CurrentDateTime, N'9780552161237')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Murder on Orient Express', N'Agatha Christie', N'HarperCollins Publisher', 175, CAST(0.09 AS Decimal(5, 2)), N'English', 2007, N'murder-on-orient-express-400x400-imadesm3hqnapjyw.jpeg', N'Murder on the Orient Express begins with Hercule Poirot boarding the Orient Express in Constantinople after solving a significant case in Palestine. On the second night of his journey, Poirot is awakened by loud noises and later finds out that the train has been stopped due to a snowstorm. Subsequently, the next morning Poirot finds out that Mr. Ratchett, who had occupied the compartment next to his, had been murdered by being stabbed twelve times in his sleep. Poirot is then called on to solve the murder and he begins his work at once, gathering evidence and listing down suspects. As he probes into the murder, Poirot finds out that the victim, Samuel Edward Ratchett, is a man with a shady past. He learns that Ratchett, known as Cassetti in the USA, had fled from the country after having being involved in the kidnapping and murder of Daisy Armstrong, a three-year-old American heiress. Poirot then discovers how Daisy’s death triggered the subsequent death of almost her entire household and soon, using his detective skills, he catches the culprit behind Ratchett’s murder.', @CurrentDateTime, N'9780007282630')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Gone Girl', N'Gillian Flynn', N'Orion Publishing Group', 350, CAST(0.42 AS Decimal(5, 2)), N'English', 2012, N'gone-girl-400x400-imadehcn4erysgcg.jpeg', N'The protanists of ne Girl are a young couple, Nick and Amy. Nick used to work as a journalist, till he lost his job. Due to the lack of income, the couple shifted their residence from New York to Nick’s hometown of Carthage. He decides to open a bar with the money from Amy’s trust fund, and works along with his twin sister, Mar. Although the three make a decent income from the bar, the couple lead a discontent life in the small town, as Amy misses New York City. As the story es on, Amy suddenly es missing. Nick is the only suspect for the police as he utilized her money to start the bar, lacked emotion on camera, and increased Amy’s life insurance. In the first half of this book, Amy and Nick talk about each other, providing contradicting views, which leave the readers in a state of suspense. In the other half of this novel, the readers come to know certain secrets about Nick and Amy. Nick has been carrying on an affair, while Amy desires to get Nick into trouble with the police by hiding from him, and making him a suspect for her so-called death. However, Amy finds herself in a big mess too. She gets robbed by certain guests of a motel. Will Amy make it through this serious mess and reunite with Nick? This book answers these questions and more. ne Girl was greatly appreciated by its readers, especially in the United States. This book was also in the New York Times Bestseller list in the year 2012 and was number 1 for 8 weeks. The book is to be adapted into a movie produced by 20th Century Fox, starring Reese Witherspoon.', @CurrentDateTime, N'9781780221359')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Murder of Roger Ackroyd', N'Agatha Christie', N'HarperCollins Publisher', 199, CAST(0.40 AS Decimal(5, 2)), N'English', 2002, N'the-murder-of-roger-ackroyd-400x400-imadag4c3rhffhhd.jpeg', N'Roger Ackroyd knew too much. He knew that the woman he loved had poisoned her brutal first husband. He suspected also that someone had been blackmailing her. Now, tragically, came the news that she had taken her own life with a drug overdose. But the evening post brought Roger one last fatal scrap of information. Unfortunately, before he could finish the letter, he was stabbed to death… Agatha Christie outraged mystery-writers and critics alike when The Murder of Roger Ackroyd, her debut novel with Collins, was published – the twist, they said, was not only unconventional but a cheat. But the book put Agatha Christie on the map and has remained one of the most accomplished and best-selling murder mysteries of all time. This special commemorative edition in Flamin Modern Classics highlights Agatha Christie’s achievement.', @CurrentDateTime, N'9780007282548')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Salvation of a Saint', N'Kei Higashino', N'Little, Brown Book Group', 350, CAST(0.40 AS Decimal(5, 2)), N'English', 2013, N'salvation-of-a-saint-400x400-imadg558fdzkvrxs.jpeg', N'Kei Higashino', @CurrentDateTime, N'9780349139340')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Thea Stilton and the Secret of the Old Castle', N'Thea Stilton', N'Scholastic Paperbacks', 275, CAST(0.29 AS Decimal(5, 2)), N'English', 2012, N'thea-stilton-and-the-secret-of-the-old-castle-400x400-imadgd5mr9vrrbmd.jpeg', N'A popular mouse author, Geronimo Stilton, works as an editor and journalist for the fictional newspaper The Rodent’s Gazette in Elisabetta Dami’s animated series. This adventure story is narrated by Geronimo’s sister, Thea Stilton. Bridget, a od friend of Thea Stilton has to come back to Scotland to be of help to her family in carrying out repairs in their old castle. The five mice are ready to help their friend as best as they can. They are shocked when Bridget is kidnapped, and rush to Scotland to find her. During the journey they come across hidden treasures, receive cryptic messages and other surprises and encounter with mysterious events.', @CurrentDateTime, N'9780545341073')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'A Memory of Light', N'Brandon Sanderson', N'Little, Brown Book Group', 799, CAST(0.37 AS Decimal(5, 2)), N'English', 2013, N'wheel-of-time-14-a-memory-of-light-400x400-imadgaw4ecpxfguc.jpeg', N'And it came to pass in those days, as it had come before and would come again, that the Dark lay heavy on the land and weighed down the hearts of men, and the green things failed, and hope died.'' - From Charal Drianaan te Calamon, The Cycle of the Dran. In the Field of Merrilor the rulers of the nations gather to join behind Rand al''Thor, or to stop him from his plan to break the seals on the Dark One''s prison - which may be a sign of his madness, or the last hope of humankind. Egwene, the Amyrlin Seat, leans toward the former. In Andor, the Trollocs seize Caemlyn. In the wolf dream, Perrin Aybara battles Slayer. Approaching Ebou Dar, Mat Cauthon plans to visit his wife Tuon, now Fortuona, Empress of the Seanchan. All humanity is in peril - and the outcome will be decided in Shayol Ghul itself. The Wheel is turning, and the Age is coming to its end. The Last Battle will determine the fate of the world. . . For twenty years The Wheel of Time has enthralled more than forty million readers in over thirty-two languages. A Memory of Light brings this majestic fantasy creation to its richly satisfying conclusion. Working from notes and partials left by Robert Jordan when he died in 2007, and consulting with Jordan''s widow, who edited all of Jordan''s books, established fantasy writer Brandon Sanderson has recreated the vision Jordan left behind.', @CurrentDateTime, N'9781841498706')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Mage''s Blood: The Montide Quartet', N'David Hair', N'Quercus', 399, CAST(0.33 AS Decimal(5, 2)), N'English', 2012, N'mage-s-blood-the-montide-quartet-400x400-imadfzka4zxhgg7z.jpeg', N'Most of the time the Moontide Bridge lies deep below the sea, but every 12 years the tides sink and the bridge is revealed, its gates open for trade. The Magi are hell-bent on ruling this new world, and for the last two Moontides they have led armies across the bridge on ''crusades'' of conquest. Now the third Moontide is almost here and, this time, the people of the East are ready for a fight ... but it is three seemingly ordinary people that will decide the fate of the world.', @CurrentDateTime, N'9781780871974')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Jurassic Park', N'Michael Crichton', N'Random House', 399, CAST(0.29 AS Decimal(5, 2)), N'English', 2006, N'jurassic-park-400x400-imadgdeh2jukhcj2.jpeg', N'Jurassic Park New ed Edition, published in 1990, is a science fiction novel about the collapse of a game park that holds genetically recreated dinosaurs. Jurassic Park New ed Edition begins in a village of Costa Rica, where several incidents involving horrific animal attacks are reported. Dr. Alan Grant, a renowned paleontologist, is  invited to a Costa Rica island to consult for a bio-engineering firm, InGen. The company is owned by John Hammond, who has developed a consumer live dinosaur preserve by duplicating rare or genetically engineered animals’ DNA. Donald Gennaro is Hammond’s lawyer, and expresses his concern about the safety of the game reserve to the consultants. Ian Malcolm, a consultant mathematician, and Hammond’s two grandchildren join the others on a tour around the island to figure out how safe the park is for visitors. Grant finds a dinosaur eggshell. He realizes that the geneticists'' design of making the dinosaurs incapable of breeding, has failed. This means that there are many more dinosaurs present on the island than previously thought. Dennis Nedry, a computer technician who works in the Jurassic Park, plans to steal dinosaur embryos from InGen’s lab. Nedry disables the entire security system, thus cutting off electricity to all fences. The visitors get stuck in their tour cars while dinosaurs escape. Jurassic Park tells a thrilling story of how these animals are completely out of control, and inflict fatal injuries to the humans. This cautionary tale tells readers how bioengineering can lead to the development of unpredictable behaviors, adaptations, and abilities in the modified creatures.', @CurrentDateTime, N'9780099282914')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Foundation', N'Isaac Asimov', N'HarperCollins', 299, CAST(0.25 AS Decimal(5, 2)), N'English', 2008, N'foundation-400x400-imadekrnpmmnqtwz.jpeg', N'For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. Only Hari Seldon, creator of the revolutionary science of psycho history, can see into the future—a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save mankind, Seldon gathers the best minds in the Empire—both scientists and scholars—and brings them to a bleak planet at the edge of the Galaxy to serve as a beacon of hope for future generations. He calls his sanctuary the Foundation. But soon the fledgling Foundation finds itself at the mercy of corrupt warlords rising in the wake of the receding Empire. And mankind’s last best hope is faced with an anizing choice: submit to the barbarians and live as slaves—or take a stand for freedom and risk total destruction.', @CurrentDateTime, N'9780007270422')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Solar', N'Ian McEwan', N'Random House', 339, CAST(0.00 AS Decimal(5, 2)), N'English', 2011, N'solar-400x400-imadhhbpk9rmc8w6.jpeg', N'Michael Beard is a Nobel prize-winning physicist whose best work is behind him. Trading on his reputation, he speaks for enormous fees, lends his name to the letterheads of renowned scientific institutions and half-heartedly heads a vernment-backed initiative tackling global warming. A compulsive womaniser, Beard finds his fifth marriage floundering. But this time it is different: she is having the affair, and he is still in love with her. When Beard’s professional and personal worlds collide in a freak accident, an opportunity presents itself for Beard to extricate himself from his marital mess, reinvirate his career and save the world from environmental disaster. Ranging from the Arctic Circle to the deserts of New Mexico, SOLAR is a serious and darkly satirical novel, showing human frailty struggling with the most pressing and complex problem of our time.A story of one man’s greed and self-deception, it is a profound and stylish new work from one of the world’s great writers.', @CurrentDateTime, N'9780099555346')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Manhattan in Reverse', N'Peter F. Hamilton', N'Macmillan', 1338, CAST(0.00 AS Decimal(5, 2)), N'English', 2011, N'manhattan-in-reverse-400x400-imadgucbxj96mfcx.jpeg', N'A collection of short stories from the master of space opera. Peter F Hamilton takes us on a journey from a murder mystery in an alternative Oxford in the 1800s to a brand new story featuring Paula Mayo, Deputy Director of the Intersolar Commonwealth’s Serious Crimes Directorate.Dealing with intricate themes and topical subject this top ten bestselling author is at the top of his game.', @CurrentDateTime, N'9780230750319')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'The Air War', N'Adrian Tchaikovsky', N'Tor', 599, CAST(0.00 AS Decimal(5, 2)), N'English', 2012, N'the-air-war-400x400-imadbhrmd4tdgqmd.jpeg', N'All is in turmoil as the world moves towards war. In Solarno, the spies watch each other and ready their knives, while Myna sees the troops muster at its border and emotions run high as it vows never to be enslaved again. In Collegium, the students argue politics, too late to turn the tide.  In the heart of the Empire, new pilots have completed their secretive training, generals are being recalled to service and armies are ready to march. Their Empress, the heir to two worlds, intends to claim her birthright. And nothing either within the Empire or beyond it will stand in her way.', @CurrentDateTime, N'9780230757004')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Dragon Reborn:wheel Of Time Book 3', N'Robert Jordan', N'Little, Brown Book Group', 350, CAST(0.00 AS Decimal(5, 2)), N'English', 1992, N'dragon-reborn-wheel-of-time-book-3-400x400-imadz74fbteazkjv.jpeg', N'At the end of the second book of The Wheel Of Time series, The Great Hunt, Rand al’Thor, having been declared the Dran Reborn, secretly leaves his camp in the Mountains of Mist and sets out for Tear to prove that he is actually the Dran Reborn. On the way, the Darkfriends and the Darkhounds hunt him. He fights the Darkhounds, defeats them, and makes an important discovery about Forsaken Sammael. At Tar Valon, Mat Cauthon defeats Gawyn Trakand. Galad Damodred escapes from Tar Valon with Thom Merrilin once he has healed and collected enough money. Elayne gives Mat a letter for her mother, Queen Morgase, to inform her that she would be leaving White Tower for a while. Mat gives the letter to the Queen and comes to know that Queen Morgase’s lover has something sinister in store for Elayne. Elsewhere, Elayne is sent with Nynaeve and Egwene to hunt down the Black Ajah. Mat es in search of Elayne to protect her. In Tear, Elayne and her companions are in trouble after being deceived by Juilin Sandar, a man who catches thieves. It remains to be seen if Mat can rescue Elayne in time. Meanwhile, Rand and the Forsaken Be’lal challenge each other to a fight. Dran Reborn: Wheel Of Time Book 3 traces the fate of all these characters and their adventures.', @CurrentDateTime, N'9781857230659')

				INSERT [dbo].[Book] ([Name], [AuthorName], [PublisherName], [Price], [Discount], [Language], [PublicationYear], [Image], [Details], [CreatedOn], [ISBN]) VALUES (N'Off Armageddon Reef', N'David Weber', N'Tor Uk', 779, CAST(0.00 AS Decimal(5, 2)), N'English', 2011, N'off-armageddon-reef-400x400-imadguwwwzrfu64z.jpeg', N'Here is the saga of humanity reduced, by an implacable alien enemy, to inhabiting a single colony on the distant world of Safehold. To avoid drawing the attention of the enemy through the busy signals of an industrial civilization, the human rulers of Safehold have taken an extraordinary measure. With mind control and hidden high technology, they have built a religion in which every Safeholdian believes, one designed to keep Safehold society medieval and unnoticed forever. After disagreement about the wisdom and justice of this course, the dissenters were ruthlessly eliminated. Centuries have passed and now, in a hidden chamber on Safehold, an android initiates a rebirth set in motion centuries before. A rebirth that will provide the only remaining humans with their last chance to learn the truth and to rejoin the universe. It is destined to be a tremendous undertaking, unfolding a story of deception and ignorance, freedom and tyranny, and the liberating power of the truth.', @CurrentDateTime, N'9780330534949')
								
		END
	COMMIT;
    PRINT 'transaction Committed';
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK;
        PRINT 'transaction rolled back';
    THROW;
END CATCH;